import { _electron as electron, expect } from '@playwright/test';
import { mkdirSync, mkdtempSync } from 'node:fs';
import { resolve, join } from 'node:path';
import assert from 'node:assert/strict';
const root = resolve('.');
mkdirSync('test-results', { recursive: true });
const dataDir = mkdtempSync(join(root, 'test-results', 'desktop-'));
const env = { ...process.env, DAYBOOK_TEST: '1', DAYBOOK_DATA_DIR: dataDir };
delete env.ELECTRON_RUN_AS_NODE;
let desktop;
const errors = [];
const launch = async () => {
  desktop = await electron.launch({ args: [root], env, timeout: 30000 });
  console.log('Electron launched');
  await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().forEach(win => win.showInactive()));
  const page = await desktop.firstWindow();
  page.setDefaultTimeout(12000);
  page.on('pageerror', e => errors.push(e.message));
  await page.getByRole('heading', { name: '今天，照自己的步調。' }).waitFor();
  console.log('App ready');
  return page;
};
try {
  let page = await launch();
  await page.screenshot({ path: 'test-results/01-empty.png' });
  await page.getByRole('button', { name: '新增事項', exact: true }).click();
  await page.getByRole('button', { name: '展開事項名稱', exact: true }).click();
  await expect(page.getByRole('option', { name: 'Meditate', exact: true })).toBeVisible();
  await page.getByRole('option', { name: 'Meditate', exact: true }).click();
  await page.getByRole('button', { name: '展開開始小時' }).click();
  await expect(page.getByRole('listbox', { name: '開始小時選項' }).getByRole('option')).toHaveCount(25);
  await page.getByRole('option', { name: '09', exact: true }).click();
  await page.getByRole('button', { name: '展開開始分鐘' }).click();
  assert.deepEqual(await page.getByRole('listbox', { name: '開始分鐘選項' }).getByRole('option').allTextContents(), ['00','05','10','15','20','25','30','35','40','45','50','55']);
  await page.getByRole('option', { name: '05', exact: true }).click();
  await page.getByRole('combobox', { name: '開始分鐘', exact: true }).fill('07');
  await page.getByRole('combobox', { name: '持續分鐘', exact: true }).fill('60');
  await page.getByLabel('重複', { exact: true }).selectOption('daily');
  await page.screenshot({ path: 'test-results/02-editor.png' });
  await page.getByRole('button', { name: '新增事項', exact: true }).last().click();
  console.log('First event submitted');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByTestId('agenda-row')).toHaveCount(1);
  let snapshot = await page.evaluate(() => window.daybook.snapshot());
  assert.match(snapshot.items[0].startAt, /T09:07$/);
  assert.match(snapshot.items[0].endAt, /T10:07$/);
  await page.getByRole('checkbox', { name: '完成 Meditate', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: '取消完成 Meditate', exact: true })).toBeChecked();
  assert.equal(await page.locator('.agenda-row.completed').evaluate(el => getComputedStyle(el, '::after').content), '""');
  await page.getByRole('checkbox', { name: '取消完成 Meditate', exact: true }).click();
  console.log('Completion toggles passed');
  await page.getByRole('button', { name: '新增事項', exact: true }).click();
  await page.getByRole('combobox', { name: '事項名稱', exact: true }).fill('跨日測試');
  await page.getByRole('combobox', { name: '開始小時', exact: true }).fill('23');
  await page.getByRole('combobox', { name: '開始分鐘', exact: true }).fill('55');
  const localDate = await page.getByLabel('開始日期', { exact: true }).inputValue();
  await page.getByLabel('結束日期', { exact: true }).fill(localDate);
  await page.getByRole('combobox', { name: '結束小時', exact: true }).fill('24');
  await page.getByRole('combobox', { name: '結束分鐘', exact: true }).fill('05');
  await page.getByRole('button', { name: '新增事項', exact: true }).last().click();
  await expect(page.getByRole('alert')).toContainText('24 點僅接受 00 分');
  await page.getByRole('combobox', { name: '結束分鐘', exact: true }).fill('00');
  await page.getByRole('button', { name: '新增事項', exact: true }).last().click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  snapshot = await page.evaluate(() => window.daybook.snapshot());
  const midnight = snapshot.items.find(i => i.title === '跨日測試');
  assert.match(midnight.endAt, /T00:00$/);
  assert.notEqual(midnight.date, midnight.endAt.slice(0, 10));
  console.log('Midnight checks passed');
  await page.getByRole('button', { name: '新增事項', exact: true }).click();
  await page.getByRole('combobox', { name: '事項名稱', exact: true }).fill('整理閱讀清單');
  await page.getByRole('button', { name: '先記成待辦', exact: true }).click();
  await page.getByRole('button', { name: '新增事項', exact: true }).last().click();
  await expect(page.getByRole('checkbox', { name: '完成 整理閱讀清單', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '偏好設定', exact: true }).click();
  await page.getByRole('button', { name: '常用事項', exact: true }).click();
  await page.getByLabel('新的常用事項', { exact: true }).fill('喝水');
  await page.getByRole('button', { name: '加入', exact: true }).click();
  await page.getByRole('button', { name: '儲存常用事項', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('常用事項已儲存');
  await page.screenshot({ path: 'test-results/03-settings.png' });
  await page.getByRole('button', { name: '一般設定', exact: true }).click();
  await page.getByRole('button', { name: '測試提醒', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('提醒小卡已顯示');
  const card = desktop.windows().find(p => p.url().endsWith('#reminder'));
  await expect(card.getByRole('main', { name: '日序提醒' })).toBeVisible();
  await card.screenshot({ path: 'test-results/1.0.1-reminder.png' });
  await card.getByRole('button', { name: '關閉提醒', exact: true }).click();
  await page.getByRole('button', { name: '關閉', exact: true }).click();
  // Add realistic fixtures through the same validated bridge in an isolated test database.
  await page.evaluate(async () => {
    const localStamp = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;
    const now = new Date(), a = new Date(+now - 15 * 60000), b = new Date(+now + 45 * 60000);
    await window.daybook.save({ value: { title: '留一段專注的時間', notes: '把通知放一邊，專心處理手上的事情。', date: localStamp(a).slice(0,10), startAt: localStamp(a), endAt: localStamp(b), repeat: { kind: 'none', weekdays: [], until: null }, reminders: [{anchor:'end',minutes:0}] } });
    const date = localStamp(now).slice(0,10);
    await window.daybook.save({ value: { title: '去健身', notes: '帶上水壺，今天練習自己喜歡的項目。', date, startAt: `${date}T18:00`, endAt: `${date}T19:00`, repeat: {kind:'weekly',weekdays:[0,2,4],until:null}, reminders:[{anchor:'start',minutes:10}] } });
  });
  await expect(page.locator('.in-progress')).not.toHaveCount(0);
  await page.screenshot({ path: 'test-results/04-agenda.png' });
  await page.getByRole('button', { name: '週', exact: true }).click();
  await expect(page.locator('.fc-timeGridWeek-view')).toBeVisible();
  await page.screenshot({ path: 'test-results/05-week.png' });
  await page.getByRole('button', { name: '月', exact: true }).click();
  await expect(page.locator('.fc-dayGridMonth-view')).toBeVisible();
  await page.screenshot({ path: 'test-results/06-month.png' });
  await page.getByRole('button', { name: '迷你視窗', exact: true }).click();
  await expect(page.locator('.mini-mode')).toBeVisible();
  const bounds = await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].getBounds());
  assert.equal(bounds.width, 390);
  await page.screenshot({ path: 'test-results/07-mini.png' });
  await page.getByRole('checkbox', { name: '完成 Meditate', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: '取消完成 Meditate', exact: true })).toBeChecked();
  await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setBounds({ x: 80, y: 90, width: 410, height: 620 }));
  await page.waitForTimeout(400);
  await page.getByRole('button', { name: '關閉視窗並在背景執行', exact: true }).click();
  assert.equal(await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isVisible()), false);
  assert.equal(await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), 1);
  await page.evaluate(() => window.daybook.windowAction('full'));
  await expect(page.locator('.mini-mode')).toHaveCount(0);
  await page.getByRole('button', { name: '日', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: '取消完成 Meditate', exact: true })).toBeChecked();
  await Promise.race([desktop.close(), new Promise((_, reject) => setTimeout(() => reject(new Error('Desktop did not quit')), 6000))]);
  page = await launch();
  snapshot = await page.evaluate(() => window.daybook.snapshot());
  assert.ok(snapshot.presets.some(p => p.title === '喝水'));
  assert.ok(snapshot.states.some(s => s.completedAt));
  await page.getByRole('button', { name: '迷你視窗', exact: true }).click();
  const restored = await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].getBounds());
  assert.equal(restored.width, 410); assert.equal(restored.height, 620);
  assert.equal(restored.x, 80); assert.equal(restored.y, 90);
  assert.deepEqual(errors, []);
  console.log('PASS: desktop inputs, presets, completion, recurrence, cross-midnight, views, mini mode, tray hiding, persistence, and window bounds.');
  console.log(`Isolated test data: ${dataDir}`);
} catch (error) {
  console.error('DESKTOP TEST FAILURE', error);
  if (desktop) { const page = desktop.windows()[0]; if (page) { console.error(await page.locator('body').innerText().catch(() => 'No page')); } }
  process.exitCode = 1;
} finally {
  if (desktop) { const proc = desktop.process(); await Promise.race([desktop.close().catch(() => {}), new Promise(r => setTimeout(r, 4000))]); proc.kill(); }
}
