import { _electron as electron, expect } from '@playwright/test';
import { mkdirSync, mkdtempSync } from 'node:fs';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
mkdirSync('test-results', { recursive: true });
const env = { ...process.env, DAYBOOK_TEST: '1', DAYBOOK_DATA_DIR: mkdtempSync(resolve('test-results/editor-review-')) };
delete env.ELECTRON_RUN_AS_NODE;
let desktop;
try {
  desktop = await electron.launch({ args: [resolve('.')], env });
  const page = await desktop.firstWindow();
  await page.locator('.workspace').waitFor();
  await page.evaluate(() => window.daybook.windowAction('full'));
  await page.getByRole('button', { name: '新增事項', exact: true }).click();
  const startHour = page.getByRole('combobox', { name: '開始小時', exact: true });
  const startMinute = page.getByRole('combobox', { name: '開始分鐘', exact: true });
  const endHour = page.getByRole('combobox', { name: '結束小時', exact: true });
  const endMinute = page.getByRole('combobox', { name: '結束分鐘', exact: true });
  const duration = page.getByRole('combobox', { name: '持續分鐘', exact: true });
  const startDate = page.getByLabel('開始日期', { exact: true });
  const endDate = page.getByLabel('結束日期', { exact: true });
  const date = await startDate.inputValue();
  await page.getByRole('combobox', { name: '事項名稱', exact: true }).fill('Duration regression');
  await startHour.fill('13');
  await startMinute.fill('00');
  await endDate.fill(date);
  await endHour.fill('15');
  await endMinute.fill('00');
  await expect(duration).toHaveValue('120');
  await startHour.fill('14');
  await startMinute.fill('');
  await startMinute.pressSequentially('30');
  await expect(duration).toHaveValue('30');
  await expect(endHour).toHaveValue('15');
  await expect(endMinute).toHaveValue('00');
  // Editing duration still moves the end; editing the start never does.
  await duration.fill('90');
  await expect(endHour).toHaveValue('16');
  await expect(endMinute).toHaveValue('00');
  await startHour.fill('16');
  await startMinute.fill('00');
  await expect(duration).toHaveValue('0');
  await page.getByRole('dialog').getByRole('button', { name: '新增事項', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('持續時間須為大於 0');
  await startHour.fill('14');
  await startMinute.fill('30');
  await endHour.fill('15');
  await page.getByRole('dialog').getByRole('button', { name: '新增事項', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const durationSaved = await page.evaluate(() => window.daybook.snapshot());
  const durationItem = durationSaved.items.find(i => i.title === 'Duration regression');
  assert.equal(durationItem.startAt, `${date}T14:30`);
  assert.equal(durationItem.endAt, `${date}T15:00`);
  await page.getByRole('button', { name: '編輯 Duration regression', exact: true }).click();
  await expect(duration).toHaveValue('30');
  await startHour.fill('13');
  await expect(duration).toHaveValue('90');
  await expect(endHour).toHaveValue('15');
  // Date changes and 24:00 must use the same calculation.
  await startDate.fill('2026-09-21');
  await endDate.fill('2026-09-22');
  await endHour.fill('01');
  await startHour.fill('24');
  await expect(duration).toHaveValue('60');
  await startDate.fill('2026-09-20');
  await expect(duration).toHaveValue('1500');
  await page.getByRole('button', { name: '取消', exact: true }).click();
  console.log('PASS: changing start recalculates duration without moving end, including saved edits and midnight.');
  const fixture = await page.evaluate(async () => {
    const d = new Date(), date = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
    for (const title of ['Review A', 'Review B']) await window.daybook.save({ value: { title, notes: `${title} note`, date, startAt: `${date}T15:00`, endAt: `${date}T16:00`, repeat: { kind: 'none', weekdays: [], until: null }, reminders: [] } });
    const items = (await window.daybook.snapshot()).items;
    return { date, a: items.find(i => i.title === 'Review A').id, b: items.find(i => i.title === 'Review B').id };
  });
  await page.getByRole('button', { name: '編輯 Review A', exact: true }).click();
  await page.getByRole('combobox', { name: '事項名稱', exact: true }).fill('Unsaved A draft');
  // Same main-process event as clicking a reminder for a different occurrence.
  await desktop.evaluate(({ BrowserWindow }, fixture) => BrowserWindow.getAllWindows()[0].webContents.send('app-event', { type: 'open', date: fixture.date, target: { itemId: fixture.b, occurrenceDate: fixture.date } }), fixture);
  await expect(page.getByRole('combobox', { name: '事項名稱', exact: true })).toHaveValue('Review B');
  await expect(page.getByLabel('備註', { exact: false })).toHaveValue('Review B note');
  await page.getByRole('button', { name: '儲存變更', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const snapshot = await page.evaluate(() => window.daybook.snapshot());
  assert.equal(snapshot.items.find(i => i.id === fixture.a).title, 'Review A');
  assert.equal(snapshot.items.find(i => i.id === fixture.b).title, 'Review B');
  await page.getByRole('button', { name: '編輯 Review B', exact: true }).click();
  await page.getByRole('button', { name: '加入提醒', exact: true }).click();
  await page.getByLabel('提醒 1 時機', { exact: true }).selectOption('custom');
  const custom = page.getByLabel('提醒 1 提前分鐘', { exact: true });
  await custom.fill('');
  await custom.pressSequentially('100');
  await expect(custom).toHaveValue('100');
  await page.getByRole('button', { name: '加入提醒', exact: true }).click();
  await page.getByLabel('提醒 2 時機', { exact: true }).selectOption('custom');
  const secondCustom = page.getByLabel('提醒 2 提前分鐘', { exact: true });
  await secondCustom.fill(''); await secondCustom.pressSequentially('10');
  await page.getByRole('button', { name: '移除提醒 1', exact: true }).click();
  await expect(custom).toHaveValue('10');
  await custom.fill('100');
  await page.getByRole('button', { name: '儲存變更', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const saved = await page.evaluate(() => window.daybook.snapshot());
  assert.equal(saved.items.find(i => i.id === fixture.b).reminders[0].minutes, 100);
  await desktop.evaluate(({ ipcMain }) => {
    ipcMain.removeHandler('save');
    ipcMain.handle('save', () => new Promise(resolve => { globalThis.finishReviewSave = resolve; }));
  });
  await page.getByRole('button', { name: '編輯 Review A', exact: true }).click();
  await page.getByRole('button', { name: '儲存變更', exact: true }).click();
  await expect(page.getByRole('button', { name: '儲存中…', exact: true })).toBeDisabled();
  await desktop.evaluate(({ BrowserWindow }, fixture) => BrowserWindow.getAllWindows()[0].webContents.send('app-event', { type: 'open', date: fixture.date, target: { itemId: fixture.b, occurrenceDate: fixture.date } }), fixture);
  await page.getByRole('combobox', { name: '事項名稱', exact: true }).fill('Keep B draft');
  await desktop.evaluate(() => globalThis.finishReviewSave());
  await page.evaluate(() => window.daybook.snapshot());
  await page.waitForTimeout(250);
  await expect(page.getByRole('combobox', { name: '事項名稱', exact: true })).toHaveValue('Keep B draft');
  console.log('PASS: opening another occurrence cannot reuse and save the previous editor draft.');
  console.log('PASS: typing custom minutes through preset values keeps the input editable.');
  console.log('PASS: completion of an earlier save does not dismiss the newly opened editor.');
} finally {
  if (desktop) { const proc = desktop.process(); await Promise.race([desktop.close().catch(() => {}), new Promise(resolve => setTimeout(resolve, 4000))]); proc.kill(); }
}
